### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by leaf-node** [cirrusidentity/simplesamlphp-module-ratelimit#12]
I see you have no LICENSE for this project. The default is proprietary.

I would suggest releasing the code under the GPL-3.0-or-later or LGPL-2.1-or-later license, the latter being used by upstream SimpleSAMLphp, so that others are encouraged to contribute changes back to your project.

Thanks! : )

**Comment by pradtke** [comment]
Thanks for the reminder @leaf-node . We've added LGPL-2.1
