### ISSUE TITLE
A bit more documentation

### ISSUE THREAD

**Issue by leaf-node** [cirrusidentity/simplesamlphp-module-ratelimit#13]
It might be obvious to some, but I got stuck on this. It would help if you mentioned that there is no need to extend the main class in this library, and that the sample configuration goes into `authsources.php`, not `config.php`. Thanks! : )

**Comment by pradtke** [comment]
Hi @leaf-node ,  We have expanded the documentation to (hopefully) make it clearer how to transition from an existing authsources configuration to one that uses rate limiting.
