### ISSUE TITLE
IP limiter doesn't work well behind reverse proxy

### ISSUE THREAD

**Issue by tvdijen** [cirrusidentity/simplesamlphp-module-ratelimit#25]
Instead of using `REMOTE_ADDR` it should be possible to configure the module to use `X-FORWARDED-FOR`... 

I just had an outage because my SNAT-address got locked out :(

**Comment by tvdijen** [comment]
Never mind, this can be fixed by properly configuring Apache

**Comment by pradtke** [comment]
@tvdijen   That sucks.   I'll make a documentation update to remind people to set the correct remoteIp stuff in apache or nginx.  Were you using the `DeviceCookieLimiter`? It should have allowed anyone using a browser they had successfully logged in through before to ignore the IP lockout and be able to attempt a log in.  If they enter the wrong password too many times than the device cookie is invalidated and they would be hit by the IP lockout.

**Comment by tvdijen** [comment]
My configuration looks like this:

```
        'ratelimit' => [
            0 => [
                'device',
                'window' => 'PT15M',
                'limit' => 10,
            ],
            1 => [
                'user',
                'window' => 'PT15M',
                'limit' => 5
            ],
            2 => [
                'password',
                'window' => 'PT15M',
                'limit' => 5
            ],
            3 => [
                'ip',
                'window' => 'PT15M',
                'limit' => 20,
                'whitelist' => [
                    '10.0.0.0/8',
                ],
            ],
        ],
```

**Comment by tvdijen** [comment]
PS: For Apache there are many ways to configure this, but since Apache 2.4 it's _very_ easy and not necessary to write complicated rules:

```
RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 10.x.x.253 10.x.x.254     <<<  Configure your SNAT-addresses here
```

And then enable `mod_remoteip` which is included in Apache already.. I think it's even enabled by default.
Docs: https://httpd.apache.org/docs/current/mod/mod_remoteip.html

**Comment by tvdijen** [comment]
> It should have allowed anyone using a browser they had successfully logged in through before to ignore the IP lockout and be able to attempt a log in.

I can't really tell if de `DeviceCookieLimiter` failed because this is an IDP where people (guests) usually only authenticate once a day/week/month.. It's not something people use multiple times a day..  It's a good case to proof with a unit test though!
